### ISSUE TITLE
Parsing error loading recipe

### ISSUE THREAD

**Issue by bookerthegeek** [chazwarp923/Unified-Items#18]
## Heyo! ##
Saw this in the console. Thought you would want to know about it. Looking forward to playing with the mod.

This did not cause a crash.
### Versions ###
 - Minecraft 1.12.2
 - forge-1.12.2-14.23.1.2575-universal.jar
 - unifieditems-1.12.2-1.7.2-206
### Revelant portion of the log ###
```
[16:58:50] [main/ERROR] [FML]: Parsing error loading recipe unifieditems:ingot_brass_alt
com.google.gson.JsonSyntaxException: Unknown item 'unifieditems:block_brass'
	at net.minecraftforge.common.crafting.CraftingHelper.getItemStackBasic(CraftingHelper.java:259) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$16(CraftingHelper.java:536) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getIngredient(CraftingHelper.java:201) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$init$15(CraftingHelper.java:523) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.getRecipe(CraftingHelper.java:408) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.lambda$loadRecipes$22(CraftingHelper.java:710) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.findFiles(CraftingHelper.java:821) ~[CraftingHelper.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:667) ~[CraftingHelper.class:?]
	at java.util.ArrayList.forEach(Unknown Source) [?:1.8.0_151]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:619) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:717) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:352) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:534) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_151]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_151]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

```
[Complete Startup Log](https://gist.github.com/bookerthegeek/7bcce558a695d1784e0964914b0f14ab)

**Comment by chazwarp923** [comment]
It's just a parsing error when trying to load the second recipe for the brass ingot. It's erroring because it can't find the brass block since its disabled. Honestly i don't like having it spit out errors about this, but forge is pushing towards hardcoded files on disk rather than the dynamic code i was using before. But it isn't going to cause you any issues so you can ignore it.

**Comment by bookerthegeek** [comment]
Have you thought about using a dynamic JSON recipe system? That way the recipe would only be registered if the materials exist.

Also, there were some more (I only put the first one here) in the log that mentioned that it could not find a recipe for a stick.

**Comment by chazwarp923** [comment]
Yeah I noticed that, forge changed how ore dictionary recipes worked. A fix is already up. As for the dynamic Json's thing, they all have to exist in the jar to be loaded at all. I cant selectively enable them. They're either there or not, no in-between.
