### ISSUE TITLE
Minecraft Crash Report

### ISSUE THREAD

**Issue by andrewq99** [chazwarp923/Unified-Items#19]
Minecraft Crash Report ----
// I blame chazwarp923, author of Unified Items.

Time: 2018-07-27 04:02:39 EDT
Description: Initializing game

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Unified Items (unifieditems)
Caused by: tech.chazwarp923.unifieditems.modular.AutoDetectMaterialsException: FIRST RUN, AUTO DETECTED ALL SUPPORTED MATERIALS, PLEASE RESTART YOUR GAME AND DO NOT REPORT THIS, IT IS INTENDED BEHAVIOR, IF YOU WOULD LIKE TO RUN THIS AGAIN, SIMPLY DELETE 'unifieditems-LastKnownMatrials.json' IN YOUR CONFIG DIRECTORY
    at tech.chazwarp923.unifieditems.modular.MaterialDetector.init(MaterialDetector.java:51)
    at tech.chazwarp923.unifieditems.proxy.CommonProxy.init(CommonProxy.java:56)
    at tech.chazwarp923.unifieditems.UnifiedItems.init(UnifiedItems.java:42)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:627)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:218)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:196)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:744)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:330)
    at net.minecraft.client.Minecraft.init(Minecraft.java:534)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3927)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 188033560 bytes (179 MB) / 536870912 bytes (512 MB) up to 1073741824 bytes (1024 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx1G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.4.2739 7 mods loaded, 7 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State | ID           | Version      | Source                            | Signature                                |
       |:----- |:------------ |:------------ |:--------------------------------- |:---------------------------------------- |
       | UCHI  | minecraft    | 1.12.2       | minecraft.jar                     | None                                     |
       | UCHI  | mcp          | 9.42         | minecraft.jar                     | None                                     |
       | UCHI  | FML          | 8.0.99.99    | forge-1.12.2-14.23.4.2739.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | forge        | 14.23.4.2739 | forge-1.12.2-14.23.4.2739.jar     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHI  | jei          | 4.9.1.175    | jei_1.12.2-4.9.1.175.jar          | None                                     |
       | UCHEE | unifieditems | 1.7.4.212    | UnifiedItems-1.12.2-1.7.4-212.jar | None                                     |
       | UCH   | vanillafix   | 1.0.9-97     | VanillaFix-1.0.9-97.jar           | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
  GL info: ' Vendor: 'Intel' Version: '4.5.0 - Build 22.20.16.4749' Renderer: 'Intel(R) UHD Graphics 620'
  Suspected Mods: Unified Items (unifieditems)
  Launched Version: 1.12.2-forge1.12.2-14.23.4.2739
  LWJGL: 2.9.4
  OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 22.20.16.4749, Intel
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz

**Comment by ghost** [comment]
@andrewq99  FIRST RUN, AUTO DETECTED ALL SUPPORTED MATERIALS, PLEASE RESTART YOUR GAME AND DO NOT REPORT THIS, IT IS INTENDED BEHAVIOR, IF YOU WOULD LIKE TO RUN THIS AGAIN, SIMPLY DELETE 'unifieditems-LastKnownMatrials.json' IN YOUR CONFIG DIRECTORY

PLEASE RESTART YOUR GAME AND DO NOT REPORT THIS, IT IS INTENDED BEHAVIOR,

DO NOT REPORT THIS, IT IS INTENDED BEHAVIOR,
