### ISSUE TITLE
Crash on Creating World

### ISSUE THREAD

**Issue by NightmareElmo** [chazwarp923/Unified-Items#3]
The game crashes during terrain generation when creating a new world. I am using verison 1.3.1
Here is the crash:
`[01:46:07] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException
    at tech.chazwarp923.unifieditems.world.WorldGenerationHandler.generate(WorldGenerationHandler.java:36) ~[WorldGenerationHandler.class:?]
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:120) ~[GameRegistry.class:?]
    at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1001) ~[asv.class:?]
    at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:983) ~[asv.class:?]
    at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:154) ~[lr.class:?]
    at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:298) ~[MinecraftServer.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:174) ~[bzl.class:?]
    at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:197) ~[bzl.class:?]
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:431) [MinecraftServer.class:?]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_101]`

**Comment by chazwarp923** [comment]
This is fixed in 1.3.2
